Change test data and propagation format
status-im/nimbus-eth1 pull request #1115
Opened 2022-06-06 16:33 UTC by KonradStaniec

Changes format of seed data from ` [header, txs, uncles]` to more natural `header, [txs, uncles], receipts]`, also add receipts to the mix.

@kdeme do we need to reseed this data to our fleet /or regenereate largare 1M block file ? I have created locally a small tool to extract this data from local geth node, so I could do that, not sure though it is necessary ?

2022-06-07 11:56 UTC, kdeme commented
The reason the format parsing is the way it is, is because these are the way the files that we got currently are formatted. Until I got some files in the right format, we shouldn't change this. (Sure I can reformat all files, but still don't have the receipts atm).



> @kdeme do we need to reseed this data to our fleet right now ? Or we may do it after we have means to propagate multiuple items at once ?

This doesn't change anything to the actual format they are send over the Portal wire. That is why the re-serialization step is in there in the first place.

2022-06-07 21:36 UTC, kdeme requested changes
As mentioned in call, lets await merging this till we have the tooling in here also to create the files.

Might also have to adjust the serialization to SSZ but that can be another PR as the protocol will have to follow this first / too.

2022-06-08 07:51 UTC, KonradStaniec commented
Yep as discussed https://github.com/status-im/nimbus-eth1/pull/1115/commits/0398a410dce8284833864bacd34168095d2409c8 adds the tool to download data from local node instance through json-rpc.

One limitation for now is that it is using premix to do the whole downloading thing, which is hardcoded to `127.0.0.1:8545` host. It is not big deal (as this is default geth host), but we may improve it at some point.

> Might also have to adjust the serialization to SSZ but that can be another PR as the protocol will have to follow this first / too.

I agree, adjusting tooling and protocol level to SSZ should be done in separate pr.

2022-06-08 09:17 UTC, kdeme commented on fluffy/tools/eth_data_exporter.nim
> +  let enc = rlp.encodeList(blck.header, blck.body, blck.receipts)
Perhaps group to 1 let

2022-06-08 09:17 UTC, kdeme commented on fluffy/tools/eth_data_exporter.nim
> +  try:
Not super important considering it is a tool, but it would be nicer / cleaner if stew/io2 calls are used here, as already done in Fluffy on other locations.

2022-06-08 09:58 UTC, KonradStaniec commented on fluffy/tools/eth_data_exporter.nim
> +  try:
I have changed it were possible although `fileOutput` still can throw as underneath it uses std lib open file.

2022-06-08 10:52 UTC, kdeme commented on fluffy/tools/eth_data_exporter.nim
> +  try:
Can put the try / except clause only over that call now then, or not?
And remove std/os import?

2022-06-08 11:41 UTC, KonradStaniec commented on fluffy/tools/eth_data_exporter.nim
> +  try:
good point about try/except, although `std/os` is still needed for path concatenation i.e `/`

2022-06-08 11:53 UTC, kdeme approved these changes

2022-06-08 13:14 UTC, merged