Update exception annotations for upcoming core db extension
status-im/nimbus-eth1 pull request #1765
Opened 2023-09-21 10:16 UTC by mjfh

2023-09-21 11:56 UTC, kdeme requested changes

2023-09-21 11:56 UTC, kdeme commented on fluffy/network/history/history_network.nim
> +proc calcRootHash(items: Transactions | PortalReceipts | Withdrawals): Hash256 {.catchRaise.} =
This shouldn't raise, where does that come from now? And I don't want to introduce this here and have it all added up in all the calls below that shouldn't raise.

I already disliked the fact that `CatchableError` was introduced lower (but before it was `RlpError`, so not a huge diff), which we have to `raiseAssert` because of that.

2023-09-21 11:56 UTC, kdeme commented on fluffy/network/history/history_network.nim
> +{.pragma: catchRaise, gcsafe, raises: [CatchableError].}
I consider these 2 type of `raises` helpers rather anti-helpers.

The first one is already implied with the `{.push raises: [].}` that we now tend to do at every file.
The second one is more like an "easy way out" with dealing with your specific exceptions.

2023-09-21 12:15 UTC, mjfh commented on fluffy/network/history/history_network.nim
> +{.pragma: catchRaise, gcsafe, raises: [CatchableError].}
The exceptions will come from the `CoreDB` database. I decided that it is not a `Defect` if the is an adjustment problem with the multi MPT descriptors. The current database interface does not support `Result[Blob,SomeError]` type. I will migrate to that but do not want to change too much at the moment.

I will prettify your fluffy code.

2023-09-21 12:53 UTC, kdeme commented on fluffy/network/history/history_network.nim
> +{.pragma: catchRaise, gcsafe, raises: [CatchableError].}
The prettify commit is not enough. Those calls simply should not raise, hence the use of `Result`.
And the fact that they raise `CatchableError` makes it even worse. As it would require an except clause for `CatchableError` where they are called, potentially missing new raises when new calls are introduced in that code.

Is it `newCoreDbRef(LegacyDbMemory).mptPrune` that raises this? I'd say a more specific error, that in our scenario cannot occur here would be more acceptable, and then it can be catched and `raiseAssert`ed.

Or perhaps we need to go back to using here the `HexaryTrie` with MemoryDb like before. It wouldn't be bad to have a "safe" hexary trie version. All that is being done here is build one from transactions/receipts/withdrawals to be able to know the roots.

2023-09-21 13:51 UTC, mjfh commented on fluffy/network/history/history_network.nim
> +{.pragma: catchRaise, gcsafe, raises: [CatchableError].}
Just note that `HexaryTrie` is not available unless you want to get locked in there.

Using exceptions are just a cheap way to proceed (with the same excuse for the `RLP` module not updated.)

But I can do better here and provide both, `Result[]` return codes and `Defect` asserts for a legacy API which would not imply any annotation changes. Errors will be opaque objects can then be decoded by a backend specific method. I will give it a try.

BTW: What is the feature of the `SafeHexaryTrie`? I have not found anything "safe". Only that key arguments are pre-hashed -- or did I miss something?

So this PR can be mothballed and eventually disposed.

2023-09-21 17:40 UTC, closed without merging

2023-09-22 06:50 UTC, kdeme commented on fluffy/network/history/history_network.nim
> +{.pragma: catchRaise, gcsafe, raises: [CatchableError].}
> Just note that `HexaryTrie` is not available unless you want to get locked in there.

Not sure what you mean with this?



> BTW: What is the feature of the `SafeHexaryTrie`? I have not found anything "safe". Only that key arguments are pre-hashed -- or did I miss something?

Well, for the use case here, which is just calculating the tree root, I would think it could be safe, as in, it does not raise exceptions.