Experimental RPC endpoints for generating block witnesses
status-im/nimbus-eth1 pull request #1977
Opened 2024-01-18 08:15 UTC by web3-developer

This change adds two new custom RPC endpoints which may be used by the Portal Network bridge node to get the changed account state for each new block. It would be impractical to query Nimbus for every account and storage slot for every block so these endpoints allow us to get just the updated state and then feed it into the portal state network. Here are the interfaces for the new endpoints:
```
proc exp_getWitnessByBlockNumber(blockId: BlockIdentifier, statePostExecution: bool): seq[byte]
proc exp_getProofsByBlockNumber(blockId: BlockIdentifier, statePostExecution: bool): seq[ProofResponse]
```

The first endpoint returns a block witness which is a binary format which follows the spec here: https://github.com/ethereum/portal-network-specs/blob/01a49a8c9bf08121ecde1b9270a6f2f679cb2568/witness.md.
The second endpoint returns a list of proofs for accounts and storage slots in the same format as the eth_getProof endpoint except it returns a list instead of a single proof.
Both endpoints support returning the state from before or after executing the transactions in the block. Each of these options would be useful in different scenarios. For example, stateless block execution would require getting the block witness data from before execution of the transactions in order to execute the transactions against the witness. For the portal network we will likely want to get the list of proofs from after execution of the block because the bridge will simply be forwarding the proofs into the portal state network and it will want the latest updated state after execution.

The new endpoints are disabled by default and can be enabled by supplying the `--rpc-api=exp` flag. `exp` is the new JSON-RPC namespace which has been added for experimental endpoints.

2024-01-18 08:32 UTC, web3-developer commented on fluffy/network/state/experimental/state_proof_types.nim
> -
Moved into the stateless folder because it likely won't be used by Fluffy and I'm now using these types in Nimbus.

2024-01-18 08:33 UTC, web3-developer commented on fluffy/network/state/experimental/state_proof_verification.nim
> -
Moved into the stateless folder because it likely won't be used by Fluffy and I'm now using these types in Nimbus.

2024-01-18 08:34 UTC, web3-developer commented on fluffy/tests/test_state_proof_verification.nim
> -      checkInvalidProofsWithBadValue(accounts, state[0], state[1])
Tests moved into stateless folder.

2024-01-18 08:37 UTC, web3-developer commented on nimbus/core/executor/process_block.nim
> +    dbTx.commit(applyDeletes = false)
I'm calling processBlock from the new RPC endpoints with commit = false.

2024-01-18 08:40 UTC, web3-developer commented on nimbus/evm/state.nim
> +    mkeys: MultikeysRef): seq[byte] {.raises: [CatchableError].} =
Added this new proc which supports getting a blockWitness by passing in a MultikeysRef. This was required in order to support returning a block witness from before execution of the transactions. Previously getting a block witness would always return the state of the updated accounts from after executing the block of transactions.

2024-01-18 08:41 UTC, web3-developer commented on nimbus/evm/state.nim
> +  buildWitness(vmState, mkeys)
This is the existing proc refactored to use the new proc above.

2024-01-18 08:46 UTC, web3-developer commented on nimbus/rpc/p2p.nim
Refactored this code out of the RPC endpoint in order to make testing easier.

2024-01-18 08:50 UTC, web3-developer commented on stateless/tree_from_witness.nim
> +proc treeNode(t: var TreeBuilder, depth: int = 0, storageMode = false): NodeKey {.gcsafe.}
I couldn't get my code to compile without adding these {.gcsafe.} pragmas for some reason. It might be related to the conditional compilation using global variables but I didn't get a chance to confirm. Not sure if this will be an issue or not.

2024-01-18 08:52 UTC, web3-developer commented on stateless/witness_verification.nim
> +
This proc is used to verify the witness data against a stateRoot and then return the data contained in the witness in a table.

2024-01-18 08:54 UTC, web3-developer commented on tests/test_blockchain_json.nim
Testing the getBlockWitness proc which contains the code to execute the block of transactions. Adding it here because we get full test coverage for all scenarios covered by the test_blockchain_json test.

2024-01-18 08:59 UTC, web3-developer commented on nimbus/rpc/experimental.nim
> +    (initialState.stateDB.rootHash, initialState.buildWitness(mkeys), flags)
We use the statePostExecution boolean flag to determine whether to return the witness using the initial state from before execution of the transactions or the state from after.

2024-01-18 08:59 UTC, web3-developer commented on nimbus/rpc/experimental.nim
> +    return @[]
Blocks with no transactions will generate an empty witness.

2024-01-18 09:57 UTC, jangko requested changes

2024-01-18 09:57 UTC, jangko commented on nimbus/core/executor/process_block.nim
> +    dbTx.commit(applyDeletes = false)
Database 'beginTransaction' should always paired with 'dispose', 'commit', or 'rollback'. If you don't call them in pair, the db tx will stay in memory.

I think what you want to achive is add another layer of db transaction and then dispose it.

Example:
'''Nim
In your rpc method
Tx=Db.BeginTransaction
Do something
Tx.dispose
'''

2024-01-18 09:57 UTC, jangko commented on tests/rpc/experimental_rpc_client.nim
> +createRpcSigs(RpcClient, currentSourcePath.parentDir / "experimental_rpc_calls.nim")
Nim-json-rpc have a new set of create rpc signature without the need to load it from file. Try it out.😁

2024-01-18 09:57 UTC, jangko commented on stateless/tree_from_witness.nim
> +proc treeNode(t: var TreeBuilder, depth: int = 0, storageMode = false): NodeKey {.gcsafe.}
It actually good to add gcsafe pragma. They are useful if you call them in a closure proc.

2024-01-18 09:57 UTC, jangko commented on tests/test_rpc_experimental_json.nim
> +      rpcServer = newRpcSocketServer(["127.0.0.1:" & $RPC_PORT])
For testing purpose, better to use port zero and let the OS choose the port for you. The new json-rpc library have server.localAddress to get the active port for your client. Doing so will prevent the next test in queue will not fail because of used port(if they use the same port).

2024-01-18 14:15 UTC, web3-developer commented on nimbus/core/executor/process_block.nim
> +    dbTx.commit(applyDeletes = false)
Yes good point. Thanks for catching this. I remember seeing that code in the eth_call RPC endpoint. I'll update.

2024-01-18 14:17 UTC, web3-developer commented on tests/rpc/experimental_rpc_client.nim
> +createRpcSigs(RpcClient, currentSourcePath.parentDir / "experimental_rpc_calls.nim")
Okay great, can you direct me to where I can see an example? Is Nimbus updated to use this new version?

2024-01-18 14:18 UTC, web3-developer commented on tests/test_rpc_experimental_json.nim
> +      rpcServer = newRpcSocketServer(["127.0.0.1:" & $RPC_PORT])
Thanks. Sure, I'll update.

2024-01-18 15:03 UTC, jangko commented on tests/rpc/experimental_rpc_client.nim
> +createRpcSigs(RpcClient, currentSourcePath.parentDir / "experimental_rpc_calls.nim")
It is being used in nim-json-rpc test and in nim-web3: 'eth_api.nim' and 'engine_api.nim'.

2024-01-19 07:32 UTC, web3-developer commented on nimbus/core/executor/process_block.nim
> +    dbTx.commit(applyDeletes = false)
Hey @jangko, actually this processBlock proc has the following lines near the top:
```
  var dbTx = vmState.com.db.beginTransaction()
  defer: dbTx.dispose()
```
It looks like dispose() will roll back the transaction already in this proc unless I'm missing something?

2024-01-19 08:14 UTC, web3-developer commented on nimbus/core/executor/process_block.nim
> +    dbTx.commit(applyDeletes = false)
@jangko If I add another transaction at a higher layer with a begin and then dispose, will the child transaction still be committed if it has a begin and commit?

2024-01-19 08:19 UTC, web3-developer commented on nimbus/core/executor/process_block.nim
> +    dbTx.commit(applyDeletes = false)
I also noticed that when the transactions are being processed the vmState.stateDB.persist is called on the AccountsCache. Will this be a problem? Or is this just pushing it to the database to be handled by the db transaction at the higher layer?

2024-01-19 08:40 UTC, jangko commented on nimbus/core/executor/process_block.nim
> +    dbTx.commit(applyDeletes = false)
> It looks like dispose() will roll back the transaction already in this proc unless I'm missing something?

It is designed to simplify the api, `dispose` will only rollback the transaction if there is exception raised and `commit` is not called. But when the transaction already commited, `dispose` is a noop. Well, actually it is a bit confusing, but we are too lazy to create a better api. It is a legacy from the beginning of nimbus project.

> If I add another transaction at a higher layer with a begin and then dispose, will the child transaction still be committed if it has a begin and commit? Or will the parent transaction prevent the child transaction from being committed?

When a database transaction started, it gives you guarantee, no children transaction will reach the database if the parent call `rollback` or `dispose`. The answer is no.
In `tracer.nim` you may see the process can be intercepted and diverted by a custom database to somewhere else. That is the only possible way to alter the database behavior. But as far as I know, block processing only use regular database transaction.

2024-01-19 08:46 UTC, jangko commented on nimbus/core/executor/process_block.nim
> +    dbTx.commit(applyDeletes = false)
> I also noticed that when the transactions are being processed the vmState.stateDB.persist is called on the AccountsCache. Will this be a problem? Or is this just pushing it to the database to be handled by the db transaction at the higher layer?

It will be handled by db transaction at higher layer. There is no backdoor or bypass mechanism. Nim is good at performing some magic, but we don't use it for state db.

2024-01-19 09:17 UTC, jangko approved these changes
LGTM

2024-01-22 09:11 UTC, merged

2024-01-23 08:56 UTC, web3-developer commented on nimbus/rpc/experimental.nim
> +    vmState = BaseVMState.new(blockHeader, com)
Good question. I did have a think about this part and basically yes we would need to be running an archive node for this to work. If pruning is enabled (in the future) and you query for an older block which doesn't exist in the db then an RPC error would be returned. It's basically a similar scenario to the existing getBlockByNumber RPC endpoint. I did test this manually by running Nimbus locally and confirmed it returns an informative RPC error.

2024-01-23 09:03 UTC, web3-developer commented on nimbus/rpc/experimental.nim
> +    {.raises: [CatchableError].} =
Good catch, thanks. I believe those exceptions shouldn't occur in practice but I'll update it to use the more specific types in my next PR anyway.

2024-01-23 12:51 UTC, kdeme commented on nimbus/rpc/experimental.nim
> +    vmState = BaseVMState.new(blockHeader, com)
My point was rather regarding the pruning of state data.
But yes, pruning of block data will/can also become applicable after EIP-4444.

2024-01-23 15:08 UTC, web3-developer commented on nimbus/rpc/experimental.nim
> +    vmState = BaseVMState.new(blockHeader, com)
Oh I see what you mean. I haven't tested this but the current implementation will likely just fail when trying to initialize the vm to the state of the parent block if the state doesn't exist. It appears to throw the CatchableError from that line. What would you expect the endpoint to return in this scenario? I think a reasonable assumption is that for this endpoint to work you will either need to run an archive node or only query recent blocks as they get created. Maybe I should try catching the CatchableError and rethrowing it with a message that explains the above assumption.

2024-01-24 01:39 UTC, web3-developer commented on nimbus/rpc/experimental.nim
> +    vmState = BaseVMState.new(blockHeader, com)
Ok sure sounds good. I'll check to make sure it doesn't throw a Defect on that line.

2024-01-24 05:24 UTC, web3-developer commented on nimbus/rpc/experimental.nim
> +    vmState = BaseVMState.new(blockHeader, com)
It looks like it does throw a defect if the stateRoot doesn't exist on initialization. I'm not sure if it's worth trying to handle this case just yet because it shouldn't be possible to trigger it until we have pruning. Perhaps I should just leave a comment in the code as a reminder to implement the check you suggested above once we have those parameters available?

2024-01-24 08:05 UTC, kdeme commented on nimbus/rpc/experimental.nim
> +    vmState = BaseVMState.new(blockHeader, com)
Yes, a comment sounds good. For now a Defect is fine, as it shouldn't be a case that can occur unless the db is corrupt or so. But when pruning gets added, that additional check may not be forgotten.