Fix multiple instances running from same dataDir
status-im/nimbus-eth1 pull request #2647
Opened 2024-09-23 10:24 UTC by bhaskar1001101

Minimum working fix for #2157 

Tested locally with `./build/fluffy --rpc` on two instances.

* Do we want to write some specific information to the lock file?
* Do we want to implement OS level locks with `io2.lockFile` to prevent other processes from writing to the lock file?

2024-09-23 16:15 UTC, kdeme approved these changes
> * Do we want to write some specific information to the lock file?

I don't think we need any extra information for this functionality. What you write now is fine I think.

> 
> * Do we want to implement OS level locks with `io2.lockFile` to prevent other processes from writing to the lock file?

I'm fine with merging this version of the PR. It's better than having no lock file.

If you want, I'm also fine with adjusting to using the specific `lockfile` call (whether in this PR or an additional one). 
We currently use it already here if you want an example: https://github.com/status-im/nimbus-eth2/blob/bf4abf8b9e07c35442b00966f51cc9af5857af33/beacon_chain/filepath.nim#L27
But that is for more sensitive data (keystore management).

2024-09-23 18:29 UTC, arnetheduck commented on fluffy/fluffy.nim
> +  if isFile(lockFilePath):
this will cause the process to fail to restart if it crashes (and the file is not removed) which is poor behavior. the normal way set up create lock files is via `flock`: https://stackoverflow.com/questions/2964391/preventing-multiple-process-instances-on-linux - this works even if the application crashes (and doesn't remove the file) - this obviously needs to be translated to nim.

2024-09-23 19:29 UTC, kdeme commented on fluffy/fluffy.nim
> +  if isFile(lockFilePath):
Yes, that's the better version, where current code gets replaced with the io2.lockFile call, basically using calls like `openLockedFile` and `closeLockedFile` from the location I linked above, or similar. No?

2024-09-24 22:26 UTC, bhaskar1001101 commented on fluffy/fluffy.nim
> +  if isFile(lockFilePath):
Added an OS managed exclusive lock.

2024-09-25 08:26 UTC, kdeme requested changes

2024-09-25 08:26 UTC, kdeme commented on fluffy/fluffy.nim
> +    error "Failed to open lock file", error = ioErrorMsg(lockFileHandleResult.error)
Considering we are quitting here, this log message should also be a `fatal` log message.

2024-09-25 08:26 UTC, kdeme commented on fluffy/fluffy.nim
> +      discard unlockFile(lockFileHandle, 0'i64, 0'i64)
The order of these two calls needs to be reversed.

I'm pretty sure that `unlockFile` here will actually fail as the file is already closed, but you wouldn't notice because of the `discard`. You wouldn't actually notice this as an issue because I assume when the program terminates the locking gets removed anyhow, but it is cleaner to fix this order of operations.

2024-09-25 08:26 UTC, kdeme commented on fluffy/fluffy.nim
> +      discard unlockFile(lockFileHandle, 0'i64, 0'i64)
Also, you can use the `unlockFile` proc that takes only the lockFileHandle as parameters: https://github.com/status-im/nim-stew/blob/master/stew/io2.nim#L1675, but you will have to pass along the `result.value` of the `lockFile` call.

2024-09-25 10:21 UTC, kdeme commented on fluffy/fluffy.nim
> +    quit 1
nitpick but it's cleaner to use `QuitFailure`

```suggestion
    quit QuitFailure
```

2024-09-26 00:17 UTC, bhaskar1001101 commented on fluffy/fluffy.nim
> +      discard unlockFile(lockFileHandle, 0'i64, 0'i64)
Made the needed changes.

2024-09-26 00:18 UTC, bhaskar1001101 commented on fluffy/fluffy.nim
> +    error "Failed to open lock file", error = ioErrorMsg(lockFileHandleResult.error)
Done

2024-09-26 06:51 UTC, kdeme approved these changes

2024-09-26 08:09 UTC, merged