Jordan/pow cache management
status-im/nimbus-eth1 pull request #888
Opened 2021-11-18 12:57 UTC by mjfh

2021-11-30 04:20 UTC, jangko requested changes

2021-11-30 04:20 UTC, jangko commented on nimbus/utils/pow.nim
> +proc init*(T: type PowRef;
It's a bit unusual for a ref object constructed using `init`. `init` usually used  for regular object, or to init ref object like the one in line 163. overloading `new` will be more consistent.

2021-11-30 04:20 UTC, jangko commented on nimbus/utils/pow.nim
> +proc init*(T: type PowRef; cache: PowCacheRef; dataset: PowDatasetRef): T =
ditto

2021-11-30 04:20 UTC, jangko commented on nimbus/utils/pow.nim
> +proc init*(T: type PowRef; rng: ref BrHmacDrbgContext): T =
ditto

2021-11-30 04:20 UTC, jangko commented on nimbus/utils/pow.nim
> +proc init*(T: type PowRef): T =
ditto

2021-11-30 04:20 UTC, jangko commented on nimbus/utils/pow/pow_cache.nim
> +proc init*(T: type PowCacheRef; maxItems = nItemsMax): T =
ditto

2021-11-30 04:20 UTC, jangko commented on nimbus/utils/pow/pow_dataset.nim
> +proc init*(T: type PowDatasetRef; maxItems = nItemsMax; cache: PowCacheRef): T =
ditto

2021-11-30 04:20 UTC, jangko commented on nimbus/utils/pow/pow_dataset.nim
> +proc init*(T: type PowDatasetRef; maxItems = nItemsMax): T =
ditto

2021-11-30 11:33 UTC, mjfh commented on nimbus/utils/pow/pow_dataset.nim
> +proc init*(T: type PowDatasetRef; maxItems = nItemsMax): T =
ok

2021-12-01 09:38 UTC, jangko commented
need rebase because of nim-json-rpc updates

2021-12-01 09:40 UTC, mjfh commented
ok thanks :)

2021-12-10 08:49 UTC, merged